language: go

go:
  - 1.13.x

services:
  - docker

before_install:
  - docker pull gcr.io/forgerock-io/am:7.0.0
  - docker run -e AM_ADMIN_PWD=password -e TOMCAT_INSECURE=ENABLED -p 8080:8080 gcr.io/forgerock-io/am:7.0.0

script: go run github.com/ForgeRock/iot-edge/v7/tests/thingsdk
